import type { DataFlowSpec } from 'react-dataflow-animator';

export const microservices: DataFlowSpec = {
  direction: 'left-to-right',
  static_objects: [
    {
      id: 'client',
      object_type: 'laptop',
      text: 'Client',
      subicon: 'react',
      lane: 1,
    },
    {
      id: 'nginx',
      object_type: 'server',
      text: 'Nginx',
      subicon: 'nginx',
      lane: 2,
    },
    {
      id: 'auth',
      object_type: 'server',
      text: 'Auth',
      subicon: 'dotnet',
      lane: 3,
    },
    {
      id: 'data',
      object_type: 'server',
      text: 'Données',
      subicon: 'node',
      lane: 3,
    },
    {
      id: 'authdb',
      object_type: 'database',
      text: 'Auth DB',
      subicon: 'postgres',
      lane: 4,
    },
    {
      id: 'datadb',
      object_type: 'database',
      text: 'Data DB',
      subicon: 'mongodb',
      lane: 4,
    },
  ],
  connections: [
    { from: 'client', to: 'nginx', style: 'dotted' },
    { from: 'nginx', to: 'auth', style: 'dotted' },
    { from: 'nginx', to: 'data', style: 'dotted' },
    { from: 'auth', to: 'authdb', style: 'dotted' },
    { from: 'data', to: 'datadb', style: 'dotted' },
  ],
  dynamic_objects: [
    {
      id: 'login',
      object_type: 'http_packet',
      packet_content: { header: 'POST /login' },
    },
    {
      id: 'authq',
      object_type: 'sql_request',
      request_content: 'SELECT * FROM users WHERE email=…',
    },
    { id: 'authr', object_type: 'sql_response', response_content: { rows: 1 } },
    {
      id: 'token',
      object_type: 'http_packet',
      packet_content: {
        header: '200 OK',
        body: { content_type: 'text', content: 'JWT' },
      },
    },
    {
      id: 'get',
      object_type: 'http_packet',
      packet_content: {
        header: 'GET /orders',
        body: { content_type: 'text', content: 'Bearer JWT' },
      },
    },
    {
      id: 'dataq',
      object_type: 'sql_request',
      request_content: 'db.orders.find()',
    },
    {
      id: 'datar',
      object_type: 'sql_response',
      response_content: { rows: 12 },
    },
    {
      id: 'json',
      object_type: 'http_packet',
      packet_content: {
        header: '200 OK',
        body: { content_type: 'text', content: '[ orders ]' },
      },
    },
  ],
  actions: [
    {
      action_type: 'comment',
      object: 'client',
      text: '1. Authentification',
      duration: 500,
    },
    {
      action_type: 'move',
      object: 'login',
      from: 'client',
      to: 'nginx',
      duration: 600,
    },
    {
      action_type: 'move',
      object: 'login',
      from: 'nginx',
      to: 'auth',
      duration: 600,
    },
    { action_type: 'loading', object: 'auth', duration: 500 },
    {
      action_type: 'move',
      object: 'authq',
      from: 'auth',
      to: 'authdb',
      duration: 600,
    },
    {
      action_type: 'loading',
      id: 'authdbwork',
      object: 'authdb',
      duration: 600,
    },
    {
      action_type: 'move',
      object: 'authr',
      from: 'authdb',
      to: 'auth',
      duration: 600,
      wait_for: 'authdbwork',
    },
    {
      action_type: 'move',
      object: 'token',
      from: 'auth',
      to: 'nginx',
      duration: 600,
    },
    {
      action_type: 'move',
      object: 'token',
      from: 'nginx',
      to: 'client',
      duration: 600,
    },
    {
      action_type: 'comment',
      object: 'client',
      text: '2. Requête de données (avec le JWT)',
      duration: 500,
    },
    {
      action_type: 'move',
      object: 'get',
      from: 'client',
      to: 'nginx',
      duration: 600,
    },
    {
      action_type: 'move',
      object: 'get',
      from: 'nginx',
      to: 'data',
      duration: 600,
    },
    { action_type: 'loading', object: 'data', duration: 500 },
    {
      action_type: 'move',
      object: 'dataq',
      from: 'data',
      to: 'datadb',
      duration: 600,
    },
    {
      action_type: 'loading',
      id: 'datadbwork',
      object: 'datadb',
      duration: 600,
    },
    {
      action_type: 'move',
      object: 'datar',
      from: 'datadb',
      to: 'data',
      duration: 600,
      wait_for: 'datadbwork',
    },
    {
      action_type: 'move',
      object: 'json',
      from: 'data',
      to: 'nginx',
      duration: 600,
    },
    {
      action_type: 'move',
      object: 'json',
      from: 'nginx',
      to: 'client',
      duration: 600,
    },
    {
      action_type: 'comment',
      object: 'client',
      text: 'Données affichées ✅',
      duration: 400,
    },
  ],
};
