/**
 * Post-processing applied to the schema generated by ts-json-schema-generator.
 * Imported by generate-schema.mjs AND check-schema-is-fresh.mjs to ensure
 * that generation and verification use exactly the same logic.
 */

/**
 * `HighlightLanguage | (string & {})` generates `anyOf: [$ref, {type:string}]`
 * in the schema, which accepts any string and defeats validation.
 * We replace it with a direct `$ref` to get strict validation
 * while preserving the non-breaking TypeScript type on the consumer side.
 *
 * @param {object} schema - The raw JSON schema (mutated in place).
 * @returns {object} The mutated schema.
 */
export function applySchemaPatches(schema) {
  schema.title = 'DataFlowSpec';

  for (const defName of ['Node', 'ObjectContent', 'PacketBody']) {
    const def = schema.definitions?.[defName];
    if (def?.properties?.language?.anyOf) {
      const ref = def.properties.language.anyOf.find((b) => b['$ref']);
      if (ref) {
        const { anyOf: _anyOf, ...rest } = def.properties.language;
        def.properties.language = { ...rest, $ref: ref['$ref'] };
      }
    }
  }
  return schema;
}
